/* 코드 낙하 — 스니펫 데이터 (교사는 이 파일만 수정해 문제를 교체/추가하세요)
 * 스키마: { id:"l{레벨}-{번호}", level:0|1|2|3, category:"...", code:"판정할 코드 그대로", exp:"한 줄 해설(선택)" }
 * 규칙(로드 시 자동 검증): 한 줄 · ASCII(0x20~0x7E)만 · 1~34자 · 선행 공백/개행/탭 없음 · id 고유.
 * level 0=비기너 1=초급 2=중급 3=고급. category는 결과 화면의 약점 분석에 쓰입니다.
 * exp(v1.5): 결과 화면 "다시 볼 코드"에서 보여줄 해설 — 생략 가능, 있으면 학습 연결이 좋아집니다.
 */
window.CODE_DROP_SNIPPETS = [
  /* ── Lv0 비기너 — 파이썬 낱말 (영타 입문: 짧은 단어, 기호 없음) ── */
  { id: "l0-01", level: 0, category: "builtin",  code: 'print',  exp: '화면에 값을 출력하는 함수' },
  { id: "l0-02", level: 0, category: "builtin",  code: 'input',  exp: '키보드 입력을 문자열로 받는 함수' },
  { id: "l0-03", level: 0, category: "builtin",  code: 'range',  exp: '연속된 정수 묶음을 만드는 함수 — for와 단짝' },
  { id: "l0-04", level: 0, category: "keyword",  code: 'for',    exp: '정해진 횟수/목록만큼 반복하는 키워드' },
  { id: "l0-05", level: 0, category: "keyword",  code: 'in',     exp: '"~안에서" — for문과 포함 검사에 쓰임' },
  { id: "l0-06", level: 0, category: "keyword",  code: 'if',     exp: '조건이 참일 때만 실행' },
  { id: "l0-07", level: 0, category: "keyword",  code: 'else',   exp: '조건이 거짓일 때 실행되는 나머지 갈래' },
  { id: "l0-08", level: 0, category: "keyword",  code: 'elif',   exp: 'else+if — 앞 조건이 거짓이면 다음 조건 검사' },
  { id: "l0-09", level: 0, category: "keyword",  code: 'while',  exp: '조건이 참인 동안 계속 반복' },
  { id: "l0-10", level: 0, category: "keyword",  code: 'def',    exp: '함수를 정의(define)하는 키워드' },
  { id: "l0-11", level: 0, category: "keyword",  code: 'return', exp: '함수의 결과를 돌려주고 즉시 종료' },
  { id: "l0-12", level: 0, category: "keyword",  code: 'import', exp: '외부 모듈을 가져오는 키워드' },
  { id: "l0-13", level: 0, category: "keyword",  code: 'True',   exp: '참 — 첫 글자가 대문자!' },
  { id: "l0-14", level: 0, category: "keyword",  code: 'False',  exp: '거짓 — 첫 글자가 대문자!' },
  { id: "l0-15", level: 0, category: "keyword",  code: 'and',    exp: '둘 다 참이어야 참' },
  { id: "l0-16", level: 0, category: "keyword",  code: 'or',     exp: '하나만 참이어도 참' },
  { id: "l0-17", level: 0, category: "keyword",  code: 'not',    exp: '참↔거짓을 뒤집기' },
  { id: "l0-18", level: 0, category: "builtin",  code: 'int',    exp: '정수형 / 정수로 변환하는 함수' },
  { id: "l0-19", level: 0, category: "builtin",  code: 'str',    exp: '문자열형 / 문자열로 변환하는 함수' },
  { id: "l0-20", level: 0, category: "builtin",  code: 'len',    exp: '길이(문자 수·원소 수)를 세는 함수' },
  { id: "l0-21", level: 0, category: "builtin",  code: 'sum',    exp: '리스트의 합을 구하는 함수' },
  { id: "l0-22", level: 0, category: "builtin",  code: 'max',    exp: '가장 큰 값을 찾는 함수' },
  { id: "l0-23", level: 0, category: "builtin",  code: 'min',    exp: '가장 작은 값을 찾는 함수' },
  { id: "l0-24", level: 0, category: "builtin",  code: 'list',   exp: '리스트형 / 리스트로 변환하는 함수' },
  { id: "l0-25", level: 0, category: "keyword",  code: 'break',  exp: '반복문을 즉시 탈출' },

  /* ── Lv1 초급 — 출력·변수·연산 ── */
  { id: "l1-01", level: 1, category: "output",   code: 'print("hello")', exp: '문자열은 따옴표로 감싸서 출력' },
  { id: "l1-02", level: 1, category: "output",   code: 'print(123)',     exp: '숫자는 따옴표 없이 그대로' },
  { id: "l1-03", level: 1, category: "variable", code: 'x = 10',         exp: '= 는 "같다"가 아니라 "담아라"(대입)' },
  { id: "l1-04", level: 1, category: "operator", code: 'y = x + 5',      exp: '오른쪽을 먼저 계산해서 왼쪽에 담는다' },
  { id: "l1-05", level: 1, category: "variable", code: 'name = "kim"',   exp: '문자열을 변수에 저장' },
  { id: "l1-06", level: 1, category: "output",   code: 'print(x)',       exp: '변수 이름엔 따옴표를 안 붙인다 — 붙이면 글자 "x"' },
  { id: "l1-07", level: 1, category: "operator", code: 'a = 3 * 4',      exp: '곱하기는 × 가 아니라 *' },
  { id: "l1-08", level: 1, category: "operator", code: 'b = 10 - 2',     exp: '빼기 연산' },
  { id: "l1-09", level: 1, category: "operator", code: 'c = 7 / 2',      exp: '/ 는 항상 실수(3.5)를 만든다' },
  { id: "l1-10", level: 1, category: "operator", code: 'd = 7 // 2',     exp: '// 는 몫만(3) — 소수점 버림' },
  { id: "l1-11", level: 1, category: "operator", code: 'e = 7 % 2',      exp: '% 는 나머지(1) — 짝홀 판별 단골' },
  { id: "l1-12", level: 1, category: "output",   code: 'print(a + b)',   exp: '괄호 안 계산 결과가 출력된다' },
  { id: "l1-13", level: 1, category: "operator", code: 'x = x + 1',      exp: '수학으론 이상하지만 "x에 1을 더해 다시 담기"' },
  { id: "l1-14", level: 1, category: "output",   code: 'print("bye")',   exp: '따옴표 짝을 정확히!' },
  { id: "l1-15", level: 1, category: "variable", code: 'age = 17',       exp: '변수 이름은 뜻이 보이게 짓는다' },
  { id: "l1-16", level: 1, category: "variable", code: 'pi = 3.14',      exp: '소수점이 있으면 실수(float)' },
  { id: "l1-17", level: 1, category: "variable", code: 's = "python"',   exp: '문자열 변수 — 따옴표 필수' },
  { id: "l1-18", level: 1, category: "output",   code: 'print(s)',       exp: '변수의 내용물이 출력된다' },
  { id: "l1-19", level: 1, category: "variable", code: 'ok = True',      exp: '불(bool) 값 저장 — True는 대문자 T' },
  { id: "l1-20", level: 1, category: "variable", code: 'no = False',     exp: '불(bool) 값 저장 — False는 대문자 F' },
  { id: "l1-21", level: 1, category: "operator", code: 'print(2 ** 3)',  exp: '** 는 거듭제곱 — 2의 3승 = 8' },
  { id: "l1-22", level: 1, category: "variable", code: 'msg = "hi"',     exp: '짧아도 어엿한 문자열' },
  { id: "l1-23", level: 1, category: "cast",     code: 'n = int("5")',   exp: '문자열 "5"를 숫자 5로 형변환' },
  { id: "l1-24", level: 1, category: "builtin",  code: 'print(len(s))',  exp: '"python"의 길이 = 6' },
  { id: "l1-25", level: 1, category: "variable", code: 'x, y = 1, 2',    exp: '한 줄에 여러 변수 동시 대입' },

  /* ── Lv2 중급 — 제어문·입력·리스트 ── */
  { id: "l2-01", level: 2, category: "condition", code: 'if x == 5:',            exp: '비교는 == 두 개! (= 하나는 대입)' },
  { id: "l2-02", level: 2, category: "condition", code: 'if x > 10:',            exp: '조건문 끝엔 콜론(:) 필수' },
  { id: "l2-03", level: 2, category: "condition", code: 'else:',                 exp: 'else엔 조건을 쓰지 않는다 — 나머지 전부' },
  { id: "l2-04", level: 2, category: "condition", code: 'elif x < 0:',           exp: '두 번째 이후 조건은 elif' },
  { id: "l2-05", level: 2, category: "loop",      code: 'for i in range(10):',   exp: '0부터 9까지 10번 반복 (10은 미포함!)' },
  { id: "l2-06", level: 2, category: "loop",      code: 'for i in range(1, 11):', exp: '1부터 10까지 — 끝 숫자는 미포함이라 11' },
  { id: "l2-07", level: 2, category: "loop",      code: 'while x < 100:',        exp: '조건이 거짓이 될 때까지 반복' },
  { id: "l2-08", level: 2, category: "input",     code: 'x = input()',           exp: 'input()의 결과는 항상 문자열!' },
  { id: "l2-09", level: 2, category: "input",     code: 'n = int(input())',      exp: '숫자로 쓰려면 int()로 감싸는 게 국룰' },
  { id: "l2-10", level: 2, category: "output",    code: 'print(i, end=" ")',     exp: 'end=" "로 줄바꿈 대신 공백 — 한 줄 출력' },
  { id: "l2-11", level: 2, category: "list",      code: 'nums = [1, 2, 3]',      exp: '리스트는 대괄호 [ ]' },
  { id: "l2-12", level: 2, category: "list",      code: 'nums.append(4)',        exp: '리스트 맨 뒤에 원소 추가' },
  { id: "l2-13", level: 2, category: "list",      code: 'print(nums[0])',        exp: '인덱스는 0부터! nums[0]은 첫 번째' },
  { id: "l2-14", level: 2, category: "builtin",   code: 'total = sum(nums)',     exp: '리스트 합계를 한 방에' },
  { id: "l2-15", level: 2, category: "condition", code: 'if x % 2 == 0:',        exp: '나머지가 0이면 짝수 — 판별 공식' },
  { id: "l2-16", level: 2, category: "output",    code: 'print("even")',         exp: '조건 안에서 결과 출력' },
  { id: "l2-17", level: 2, category: "loop",      code: 'for n in nums:',        exp: '리스트 원소를 하나씩 꺼내는 반복' },
  { id: "l2-18", level: 2, category: "loop",      code: 'while True:',           exp: '무한 반복 — 안에 break가 꼭 필요' },
  { id: "l2-19", level: 2, category: "loop",      code: 'break',                 exp: '가장 가까운 반복문 하나만 탈출' },
  { id: "l2-20", level: 2, category: "loop",      code: 'continue',              exp: '이번 회차만 건너뛰고 다음 반복으로' },
  { id: "l2-21", level: 2, category: "string",    code: 'print(f"x = {x}")',     exp: 'f-문자열 — 중괄호 안에 변수를 끼워 넣기' },
  { id: "l2-22", level: 2, category: "cast",      code: 's = str(99)',           exp: '숫자를 문자열로 형변환' },
  { id: "l2-23", level: 2, category: "condition", code: 'if a and b:',           exp: '두 조건이 모두 참일 때만' },
  { id: "l2-24", level: 2, category: "condition", code: 'if not done:',          exp: '"아직 안 끝났다면" — 불 값 뒤집기' },
  { id: "l2-25", level: 2, category: "builtin",   code: 'print(max(nums))',      exp: '리스트에서 최댓값 찾기' },

  /* ── Lv3 고급 — 함수·자료구조·모듈 ── */
  { id: "l3-01", level: 3, category: "function",      code: 'def add(a, b):',                exp: '매개변수 a, b를 받는 함수 정의' },
  { id: "l3-02", level: 3, category: "function",      code: 'return a + b',                  exp: '계산 결과를 호출한 곳으로 반환' },
  { id: "l3-03", level: 3, category: "function",      code: 'def main():',                   exp: '매개변수 없는 함수도 괄호는 필수' },
  { id: "l3-04", level: 3, category: "dict",          code: 'd = {"a": 1}',                  exp: '딕셔너리 — 키:값 쌍, 중괄호 { }' },
  { id: "l3-05", level: 3, category: "dict",          code: 'print(d["a"])',                 exp: '키로 값을 꺼낸다 (인덱스가 아니라 키!)' },
  { id: "l3-06", level: 3, category: "dict",          code: 'd["b"] = 2',                    exp: '새 키에 대입하면 항목이 추가된다' },
  { id: "l3-07", level: 3, category: "dict",          code: 'keys = list(d.keys())',         exp: '키 목록을 리스트로 변환' },
  { id: "l3-08", level: 3, category: "comprehension", code: 'sq = [i**2 for i in range(10)]', exp: '리스트 컴프리헨션 — for문을 한 줄로' },
  { id: "l3-09", level: 3, category: "comprehension", code: 'ev = [n for n in nums if n%2==0]', exp: '조건까지 넣어 걸러 담기' },
  { id: "l3-10", level: 3, category: "slice",         code: 'part = nums[1:3]',              exp: '슬라이싱 — 1번부터 3번 앞까지(2개)' },
  { id: "l3-11", level: 3, category: "slice",         code: 'rev = nums[::-1]',              exp: '스텝 -1 = 뒤집기 한 줄 비법' },
  { id: "l3-12", level: 3, category: "exception",     code: 'try:',                          exp: '오류가 날 수 있는 코드를 감싸기' },
  { id: "l3-13", level: 3, category: "exception",     code: 'except ValueError:',            exp: '특정 오류가 나면 여기로 점프' },
  { id: "l3-14", level: 3, category: "module",        code: 'import random',                 exp: '난수 모듈 가져오기' },
  { id: "l3-15", level: 3, category: "module",        code: 'n = random.randint(1, 6)',      exp: '1~6 주사위 — randint는 양 끝 포함' },
  { id: "l3-16", level: 3, category: "module",        code: 'from math import sqrt',         exp: '모듈에서 필요한 함수만 골라 가져오기' },
  { id: "l3-17", level: 3, category: "module",        code: 'print(sqrt(16))',               exp: '제곱근 — 결과는 4.0 (실수)' },
  { id: "l3-18", level: 3, category: "function",      code: 'def fib(n):',                   exp: '재귀 함수의 시작 — 자기 자신을 부른다' },
  { id: "l3-19", level: 3, category: "function",      code: 'return fib(n-1) + fib(n-2)',    exp: '피보나치 재귀 단계 — 기저 조건 필수!' },
  { id: "l3-20", level: 3, category: "function",      code: 'f = lambda x: x * 2',           exp: '람다 — 이름 없는 한 줄 함수' },
  { id: "l3-21", level: 3, category: "builtin",       code: 'sorted(nums, reverse=True)',    exp: '내림차순 정렬 — 원본은 그대로' },
  { id: "l3-22", level: 3, category: "tuple",         code: 't = (1, 2, 3)',                 exp: '튜플 — 리스트와 달리 수정 불가' },
  { id: "l3-23", level: 3, category: "variable",      code: 'a, b = b, a',                   exp: '파이썬식 맞바꿈 — 임시 변수 불필요' },
  { id: "l3-24", level: 3, category: "dict",          code: 'for k, v in d.items():',        exp: '딕셔너리의 키와 값을 동시에 순회' },
  { id: "l3-25", level: 3, category: "builtin",       code: 'print(round(3.567, 2))',        exp: '소수 둘째 자리까지 반올림 → 3.57' },
];
