/* 코드 낙하 — 스니펫 데이터 (교사는 이 파일만 수정해 문제를 교체/추가하세요)
 * 스키마: { id:"l{레벨}-{번호}", level:0|1|2|3, category:"...", code:"판정할 코드 그대로" }
 * 규칙(로드 시 자동 검증): 한 줄 · ASCII(0x20~0x7E)만 · 1~34자 · 선행 공백/개행/탭 없음 · id 고유.
 * level 0=비기너 1=초급 2=중급 3=고급. category는 결과 화면의 약점 분석에 쓰입니다.
 */
window.CODE_DROP_SNIPPETS = [
  /* ── Lv0 비기너 — 파이썬 낱말 (영타 입문: 짧은 단어, 기호 없음) ── */
  { id: "l0-01", level: 0, category: "builtin",  code: 'print' },
  { id: "l0-02", level: 0, category: "builtin",  code: 'input' },
  { id: "l0-03", level: 0, category: "builtin",  code: 'range' },
  { id: "l0-04", level: 0, category: "keyword",  code: 'for' },
  { id: "l0-05", level: 0, category: "keyword",  code: 'in' },
  { id: "l0-06", level: 0, category: "keyword",  code: 'if' },
  { id: "l0-07", level: 0, category: "keyword",  code: 'else' },
  { id: "l0-08", level: 0, category: "keyword",  code: 'elif' },
  { id: "l0-09", level: 0, category: "keyword",  code: 'while' },
  { id: "l0-10", level: 0, category: "keyword",  code: 'def' },
  { id: "l0-11", level: 0, category: "keyword",  code: 'return' },
  { id: "l0-12", level: 0, category: "keyword",  code: 'import' },
  { id: "l0-13", level: 0, category: "keyword",  code: 'True' },
  { id: "l0-14", level: 0, category: "keyword",  code: 'False' },
  { id: "l0-15", level: 0, category: "keyword",  code: 'and' },
  { id: "l0-16", level: 0, category: "keyword",  code: 'or' },
  { id: "l0-17", level: 0, category: "keyword",  code: 'not' },
  { id: "l0-18", level: 0, category: "builtin",  code: 'int' },
  { id: "l0-19", level: 0, category: "builtin",  code: 'str' },
  { id: "l0-20", level: 0, category: "builtin",  code: 'len' },
  { id: "l0-21", level: 0, category: "builtin",  code: 'sum' },
  { id: "l0-22", level: 0, category: "builtin",  code: 'max' },
  { id: "l0-23", level: 0, category: "builtin",  code: 'min' },
  { id: "l0-24", level: 0, category: "builtin",  code: 'list' },
  { id: "l0-25", level: 0, category: "keyword",  code: 'break' },

  /* ── Lv1 초급 — 출력·변수·연산 ── */
  { id: "l1-01", level: 1, category: "output",   code: 'print("hello")' },
  { id: "l1-02", level: 1, category: "output",   code: 'print(123)' },
  { id: "l1-03", level: 1, category: "variable", code: 'x = 10' },
  { id: "l1-04", level: 1, category: "operator", code: 'y = x + 5' },
  { id: "l1-05", level: 1, category: "variable", code: 'name = "kim"' },
  { id: "l1-06", level: 1, category: "output",   code: 'print(x)' },
  { id: "l1-07", level: 1, category: "operator", code: 'a = 3 * 4' },
  { id: "l1-08", level: 1, category: "operator", code: 'b = 10 - 2' },
  { id: "l1-09", level: 1, category: "operator", code: 'c = 7 / 2' },
  { id: "l1-10", level: 1, category: "operator", code: 'd = 7 // 2' },
  { id: "l1-11", level: 1, category: "operator", code: 'e = 7 % 2' },
  { id: "l1-12", level: 1, category: "output",   code: 'print(a + b)' },
  { id: "l1-13", level: 1, category: "operator", code: 'x = x + 1' },
  { id: "l1-14", level: 1, category: "output",   code: 'print("bye")' },
  { id: "l1-15", level: 1, category: "variable", code: 'age = 17' },
  { id: "l1-16", level: 1, category: "variable", code: 'pi = 3.14' },
  { id: "l1-17", level: 1, category: "variable", code: 's = "python"' },
  { id: "l1-18", level: 1, category: "output",   code: 'print(s)' },
  { id: "l1-19", level: 1, category: "variable", code: 'ok = True' },
  { id: "l1-20", level: 1, category: "variable", code: 'no = False' },
  { id: "l1-21", level: 1, category: "operator", code: 'print(2 ** 3)' },
  { id: "l1-22", level: 1, category: "variable", code: 'msg = "hi"' },
  { id: "l1-23", level: 1, category: "cast",     code: 'n = int("5")' },
  { id: "l1-24", level: 1, category: "builtin",  code: 'print(len(s))' },
  { id: "l1-25", level: 1, category: "variable", code: 'x, y = 1, 2' },

  /* ── Lv2 중급 — 제어문·입력·리스트 ── */
  { id: "l2-01", level: 2, category: "condition", code: 'if x == 5:' },
  { id: "l2-02", level: 2, category: "condition", code: 'if x > 10:' },
  { id: "l2-03", level: 2, category: "condition", code: 'else:' },
  { id: "l2-04", level: 2, category: "condition", code: 'elif x < 0:' },
  { id: "l2-05", level: 2, category: "loop",      code: 'for i in range(10):' },
  { id: "l2-06", level: 2, category: "loop",      code: 'for i in range(1, 11):' },
  { id: "l2-07", level: 2, category: "loop",      code: 'while x < 100:' },
  { id: "l2-08", level: 2, category: "input",     code: 'x = input()' },
  { id: "l2-09", level: 2, category: "input",     code: 'n = int(input())' },
  { id: "l2-10", level: 2, category: "output",    code: 'print(i, end=" ")' },
  { id: "l2-11", level: 2, category: "list",      code: 'nums = [1, 2, 3]' },
  { id: "l2-12", level: 2, category: "list",      code: 'nums.append(4)' },
  { id: "l2-13", level: 2, category: "list",      code: 'print(nums[0])' },
  { id: "l2-14", level: 2, category: "builtin",   code: 'total = sum(nums)' },
  { id: "l2-15", level: 2, category: "condition", code: 'if x % 2 == 0:' },
  { id: "l2-16", level: 2, category: "output",    code: 'print("even")' },
  { id: "l2-17", level: 2, category: "loop",      code: 'for n in nums:' },
  { id: "l2-18", level: 2, category: "loop",      code: 'while True:' },
  { id: "l2-19", level: 2, category: "loop",      code: 'break' },
  { id: "l2-20", level: 2, category: "loop",      code: 'continue' },
  { id: "l2-21", level: 2, category: "string",    code: 'print(f"x = {x}")' },
  { id: "l2-22", level: 2, category: "cast",      code: 's = str(99)' },
  { id: "l2-23", level: 2, category: "condition", code: 'if a and b:' },
  { id: "l2-24", level: 2, category: "condition", code: 'if not done:' },
  { id: "l2-25", level: 2, category: "builtin",   code: 'print(max(nums))' },

  /* ── Lv3 고급 — 함수·자료구조·모듈 ── */
  { id: "l3-01", level: 3, category: "function",      code: 'def add(a, b):' },
  { id: "l3-02", level: 3, category: "function",      code: 'return a + b' },
  { id: "l3-03", level: 3, category: "function",      code: 'def main():' },
  { id: "l3-04", level: 3, category: "dict",          code: 'd = {"a": 1}' },
  { id: "l3-05", level: 3, category: "dict",          code: 'print(d["a"])' },
  { id: "l3-06", level: 3, category: "dict",          code: 'd["b"] = 2' },
  { id: "l3-07", level: 3, category: "dict",          code: 'keys = list(d.keys())' },
  { id: "l3-08", level: 3, category: "comprehension", code: 'sq = [i**2 for i in range(10)]' },
  { id: "l3-09", level: 3, category: "comprehension", code: 'ev = [n for n in nums if n%2==0]' },
  { id: "l3-10", level: 3, category: "slice",         code: 'part = nums[1:3]' },
  { id: "l3-11", level: 3, category: "slice",         code: 'rev = nums[::-1]' },
  { id: "l3-12", level: 3, category: "exception",     code: 'try:' },
  { id: "l3-13", level: 3, category: "exception",     code: 'except ValueError:' },
  { id: "l3-14", level: 3, category: "module",        code: 'import random' },
  { id: "l3-15", level: 3, category: "module",        code: 'n = random.randint(1, 6)' },
  { id: "l3-16", level: 3, category: "module",        code: 'from math import sqrt' },
  { id: "l3-17", level: 3, category: "module",        code: 'print(sqrt(16))' },
  { id: "l3-18", level: 3, category: "function",      code: 'def fib(n):' },
  { id: "l3-19", level: 3, category: "function",      code: 'return fib(n-1) + fib(n-2)' },
  { id: "l3-20", level: 3, category: "function",      code: 'f = lambda x: x * 2' },
  { id: "l3-21", level: 3, category: "builtin",       code: 'sorted(nums, reverse=True)' },
  { id: "l3-22", level: 3, category: "tuple",         code: 't = (1, 2, 3)' },
  { id: "l3-23", level: 3, category: "variable",      code: 'a, b = b, a' },
  { id: "l3-24", level: 3, category: "dict",          code: 'for k, v in d.items():' },
  { id: "l3-25", level: 3, category: "builtin",       code: 'print(round(3.567, 2))' },
];
